CREATE TABLE IF NOT EXISTS {ATHENA_DB}.{VEHICLES_DATA}
WITH(
partitioned_by=ARRAY['VEHICLE_TYPE'],
format='PARQUET',
write_compression='SNAPPY',
external_location='s3://{S3_BUCKET}/{VEHICLES_DATA}/'
) AS
SELECT DISTINCT
    VEHICLE_ID,
    VEHICLE_NAME,
    VEHICLE_TYPE
FROM {ATHENA_DB}.{RAW_VEHICLES_DATA}
;
