INSERT INTO {ATHENA_DB}.{VEHICLES_DATA} (
    VEHICLE_ID,
    VEHICLE_NAME,
    VEHICLE_TYPE
)
SELECT DISTINCT
    a.VEHICLE_ID,
    a.VEHICLE_NAME,
    a.VEHICLE_TYPE
FROM {ATHENA_DB}.{RAW_VEHICLES_DATA} a
LEFT JOIN {ATHENA_DB}.{VEHICLES_DATA} b
ON(a.VEHICLE_ID=b.VEHICLE_ID and a.VEHICLE_NAME=b.VEHICLE_NAME and a.VEHICLE_TYPE=b.VEHICLE_TYPE)
WHERE b.VEHICLE_ID IS NULL
;
